# Generated by Django 3.2.14 on 2022-08-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220724_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tage',
            new_name='tags',
        ),
    ]
